
services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
        - 27017:27017
        environment:
        - MONGO_INITDB_ROOT_USERNAME=username
        - MONGO_INITDB_ROOT_PASSWORD=password
        networks:
            main:
                aliases:
                    - database

networks:
    main: